# RTAB-Map configuration for streaming LiDAR point clouds
# Nodes: rtabmap_slam/rtabmap and rtabmap_odom/icp_odometry.

rtabmap:
  ros__parameters:
    use_sim_time: false
    frame_id: lidar_link
    map_frame_id: map
    odom_frame_id: odom
    publish_tf: true
    subscribe_depth: false
    subscribe_rgb: false
    subscribe_rgbd: false
    subscribe_scan: false
    subscribe_scan_cloud: true
    subscribe_stereo: false
    subscribe_user_data: false
    subscribe_odom_info: true
    queue_size: 10
    approx_sync: false
    detection_rate: 1.0
    Mem/NotLinkedNodesKept: "true"
    Mem/STMSize: "30"
    RGBD/ProximityPathMaxNeighbors: "1"
    RGBD/LoopClosureHypothesis: "5"
    RGBD/LoopClosureIcpType: "1"
    RGBD/LinearUpdate: "0"
    RGBD/AngularUpdate: "0"
    Optimizer/GravitySigma: "0"
    SLAM/Strategy: "1"
    Reg/Strategy: "1"
    Icp/CorrespondenceRatio: "0.1"
    Icp/Iterations: "30"
    Icp/Epsilon: "0.001"
    Grid/3D: "true"
    Grid/Sensor: "true"
    Grid/CellSize: "0.2"
    Grid/ClusterRadius: "0.5"
    Voxel/Size: "0.2"
    Rtabmap/SaveWMState: "false"
    Rtabmap/SavePointCloud: "true"

icp_odometry:
  ros__parameters:
    use_sim_time: false
    frame_id: lidar_link
    odom_frame_id: odom
    publish_tf: true
    wait_for_transform: 0.2
    deskewing: false
    approx_sync: false
    queue_size: 5
    expected_update_rate: 0.0
    scan_cloud_max_pts: 120000
    scan_cloud_min_pts: 50
    Icp/PointToPlane: "true"
    Icp/VoxelSize: "0.2"
    Icp/Epsilon: "0.001"
    Icp/CorrespondenceRatio: "0.1"
    Icp/Iterations: "30"
    Icp/PointToPlaneK: "20"
    Icp/PointToPlaneRadius: "0"
    Odom/ScanKeyFrameThr: "0.4"
    OdomF2M/ScanSubtractRadius: "0.2"
    OdomF2M/ScanMaxSize: "15000"
    OdomF2M/BundleAdjustment: "false"
